In [2]:
#load relevant modules
import pandas as pd
import numpy as np

#Expand display for dataframe 
pd.options.display.max_columns = 50

In [3]:
#import dataset
df = pd.read_csv("diabetic_data.csv")
df.shape
# df.head()

(101766, 50)

In [4]:
df_1 = df.replace('?', None)
df_1.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),None,6,25,1,1,None,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,None,None,1,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),None,1,1,7,3,None,None,59,0,18,0,0,0,276,250.01,255,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),None,1,1,7,2,None,None,11,5,13,2,0,1,648,250,V27,6,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),None,1,1,7,2,None,None,44,1,16,0,0,0,8,250.43,403,7,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),None,1,1,7,1,None,None,51,0,8,0,0,0,197,157,250,5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [ ]:
#to check the number of missing values accross the colums
df_1.isnull().sum()

In [6]:
#remove columns with too many missing values
df_2 = df_1.drop(['weight', 'payer_code', 'medical_specialty','A1Cresult', 'max_glu_serum'], axis = 1)

df_2.shape

(101766, 45)

In [7]:
df_3 = df_2.dropna()
df_3.shape

(98053, 45)

In [8]:
df_3.isnull().any().any()

False

In [9]:
#to reset index
df_4 = df_3.reset_index(drop = True)

In [10]:
df_4.head()

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
1,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,11,5,13,2,0,1,648,250,V27,6,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
2,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,44,1,16,0,0,0,8,250.43,403,7,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
3,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,51,0,8,0,0,0,197,157,250,5,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
4,35754,82637451,Caucasian,Male,[50-60),2,1,2,3,31,6,16,0,0,0,414,411,250,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30

In [11]:
df_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98053 entries, 0 to 98052
Data columns (total 45 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   encounter_id              98053 non-null  int64
 1   patient_nbr               98053 non-null  int64
 2   race                      98053 non-null  object
 3   gender                    98053 non-null  object
 4   age                       98053 non-null  object
 5   admission_type_id         98053 non-null  int64
 6   discharge_disposition_id  98053 non-null  int64
 7   admission_source_id       98053 non-null  int64
 8   time_in_hospital          98053 non-null  int64
 9   num_lab_procedures        98053 non-null  int64
 10  num_procedures            98053 non-null  int64
 11  num_medications           98053 non-null  int64
 12  number_outpatient         98053 non-null  int64
 13  number_emergency          98053 non-null  int64
 14  number_inpatient          98053 non-null  int64
 15  diag_1                    98053 non-null  object
 16  diag_2                    98053 non-null  object
 17  diag_3                    98053 non-null  object
 18  number_diagnoses          98053 non-null  int64
 19  metformin                 98053 non-null  object
 20  repaglinide               98053 non-null  object
 21  nateglinide               98053 non-null  object
 22  chlorpropamide            98053 non-null  object
 23  glimepiride               98053 non-null  object
 24  acetohexamide             98053 non-null  object
 25  glipizide                 98053 non-null  object
 26  glyburide                 98053 non-null  object
 27  tolbutamide               98053 non-null  object
 28  pioglitazone              98053 non-null  object
 29  rosiglitazone             98053 non-null  object
 30  acarbose                  98053 non-null  object
 31  miglitol                  98053 non-null  object
 32  troglitazone              98053 non-null  object
 33  tolazamide                98053 non-null  object
 34  examide                   98053 non-null  object
 35  citoglipton               98053 non-null  object
 36  insulin                   98053 non-null  object
 37  glyburide-metformin       98053 non-null  object
 38  glipizide-metformin       98053 non-null  object
 39  glimepiride-pioglitazone  98053 non-null  object
 40  metformin-rosiglitazone   98053 non-null  object
 41  metformin-pioglitazone    98053 non-null  object
 42  change                    98053 non-null  object
 43  diabetesMed               98053 non-null  object
 44  readmitted                98053 non-null  object
dtypes: int64(13), object(32)
memory usage: 33.7+ MB

In [12]:
df_4['readmitted'].unique()

array(['>30', 'NO', '<30'], dtype=object)

In [13]:
#df_4.diag_1.count()

#print(df[df['diag_1'].str.contains('V5')])

#print(df['diag_1'].isin(['V57']))

print('V57' in set(df_4['diag_1']))

True

In [14]:
#try to filter out none numeric in the column
pattern = "V", "E"
filter_df = df_4["diag_1"].str.startswith(pattern)
sum(filter_df)

1601

In [15]:
df_5 = df_4[~filter_df]
df_5.shape

(96452, 45)

In [16]:
#to reset index
df_5 = df_5.reset_index(drop = True)
# df_5.head()

In [17]:
#filter out none numeric in the column
pattern = "V", "E"
filter_df_1 = df_5["diag_2"].str.startswith(pattern)
sum(filter_df_1)

2234

In [18]:
df_6 = df_5[~filter_df_1]
df_6.shape

(94218, 45)

In [19]:
#to reset index
df_6 = df_6.reset_index(drop = True)
# df_6.head()

In [20]:
#try to filter out none numeric in the column
pattern = "V", "E"
filter_df_2 = df_6["diag_3"].str.startswith(pattern)
sum(filter_df_2)

4436

In [21]:
df_7 = df_6[~filter_df_2]
df_7.shape

(89782, 45)

In [22]:
#to reset index
df_7 = df_7.reset_index(drop = True)
# df_7.head()

In [23]:
#duplicate and rename readmitted column
df_7['class'] = df_7['readmitted']

# df_7.head()

In [24]:
# Replace the values of class coulumn
df_7['class'] = df_7['class'].replace('>30', 'Readmission')
df_7['class'] = df_7['class'].replace('<30', 'Readmission')
df_7['class'] = df_7['class'].replace('NO', 'No_readmission')
# df_7.head()

In [25]:
# to delete the column readmitted 
del df_7['readmitted']
# df_7.head()

In [26]:
df_7['race'].unique()

array(['Caucasian', 'AfricanAmerican', 'Other', 'Asian', 'Hispanic'],
      dtype=object)

In [27]:
df_7['gender'].unique()

array(['Female', 'Male', 'Unknown/Invalid'], dtype=object)

In [28]:
#try to filter out none numeric in the column
pattern = "U"
filter_df_3 = df_7["gender"].str.startswith(pattern)
sum(filter_df_3)

1

In [29]:
df_8 = df_7[~filter_df_3]
df_8.shape

(89781, 45)

In [30]:
#to reset index
df_8 = df_8.reset_index(drop = True)
# df_8.head(50)

In [31]:
df_8['diabetesMed'].unique()

array(['Yes', 'No'], dtype=object)

In [32]:
# Applying OneHot Encoding to columns with none nominal variable
df2=pd.get_dummies(df_8[["race", "gender"]])
df_new=pd.concat([df_8,df2],axis=1)
df_new = df_new.drop(['race', 'gender'], axis = 1)
# df_new.head()

In [33]:
#duplicate and rename age column
df_new['avg_age'] = df_new['age']

# df_new.head()

In [34]:
# Replace the values of avg_age coulumn
df_new['avg_age'] = df_new['avg_age'].replace('[0-10)', '5')
df_new['avg_age'] = df_new['avg_age'].replace('[10-20)', '15')
df_new['avg_age'] = df_new['avg_age'].replace('[20-30)', '25')
df_new['avg_age'] = df_new['avg_age'].replace('[30-40)', '35')
df_new['avg_age'] = df_new['avg_age'].replace('[40-50)', '45')
df_new['avg_age'] = df_new['avg_age'].replace('[50-60)', '55')
df_new['avg_age'] = df_new['avg_age'].replace('[60-70)', '65')
df_new['avg_age'] = df_new['avg_age'].replace('[70-80)', '75')
df_new['avg_age'] = df_new['avg_age'].replace('[80-90)', '85')
df_new['avg_age'] = df_new['avg_age'].replace('[90-100)', '95')
# df_new.head()
# df_new.info()

In [35]:
# to delete a column 
del df_new['age']
df_new.head()
# df_new.info

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,class,race_AfricanAmerican,race_Asian,race_Caucasian,race_Hispanic,race_Other,gender_Female,gender_Male,avg_age
0,149190,55629189,1,1,7,3,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,Readmission,0,0,1,0,0,1,0,15
1,500364,82442376,1,1,7,2,44,1,16,0,0,0,8,250.43,403,7,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,No_readmission,0,0,1,0,0,0,1,35
2,16680,42519267,1,1,7,1,51,0,8,0,0,0,197,157,250,5,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,No_readmission,0,0,1,0,0,0,1,45
3,35754,82637451,2,1,2,3,31,6,16,0,0,0,414,411,250,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,Readmission,0,0,1,0,0,0,1,55
4,63768,114882984,1,1,7,5,73,0,12,0,0,0,428,492,250,8,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,Readmission,0,0,1,0,0,0,1,75

In [36]:
# move column class to the last

df_new.insert(49, 'class', df_new.pop('class'))
df_new.head()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,race_AfricanAmerican,race_Asian,race_Caucasian,race_Hispanic,race_Other,gender_Female,gender_Male,avg_age,class
0,149190,55629189,1,1,7,3,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,0,0,1,0,0,1,0,15,Readmission
1,500364,82442376,1,1,7,2,44,1,16,0,0,0,8,250.43,403,7,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,0,0,1,0,0,0,1,35,No_readmission
2,16680,42519267,1,1,7,1,51,0,8,0,0,0,197,157,250,5,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,0,0,1,0,0,0,1,45,No_readmission
3,35754,82637451,2,1,2,3,31,6,16,0,0,0,414,411,250,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,0,0,1,0,0,0,1,55,Readmission
4,63768,114882984,1,1,7,5,73,0,12,0,0,0,428,492,250,8,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,0,0,1,0,0,0,1,75,Readmission

In [37]:
from sklearn.preprocessing import OrdinalEncoder

In [38]:
enc = OrdinalEncoder()
print(enc)

OrdinalEncoder()

In [39]:
# enc.fit_transform(df_new[["metformin"]])

In [40]:
df_new[["metformin", "repaglinide", "nateglinide", "chlorpropamide", "glimepiride", "acetohexamide", "glipizide", "glyburide", "tolbutamide", "pioglitazone", "rosiglitazone", "acarbose", "miglitol", "troglitazone", "tolazamide", "examide", "citoglipton", "insulin", "glyburide-metformin", "glipizide-metformin", "glimepiride-pioglitazone", "metformin-rosiglitazone", "metformin-pioglitazone", "change", "diabetesMed"]] = enc.fit_transform(df_new[["metformin", "repaglinide", "nateglinide", "chlorpropamide", "glimepiride", "acetohexamide", "glipizide", "glyburide", "tolbutamide", "pioglitazone", "rosiglitazone", "acarbose", "miglitol", "troglitazone", "tolazamide", "examide", "citoglipton", "insulin", "glyburide-metformin", "glipizide-metformin", "glimepiride-pioglitazone", "metformin-rosiglitazone", "metformin-pioglitazone", "change", "diabetesMed"]])
df_new.head()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,race_AfricanAmerican,race_Asian,race_Caucasian,race_Hispanic,race_Other,gender_Female,gender_Male,avg_age,class
0,149190,55629189,1,1,7,3,59,0,18,0,0,0,276,250.01,255,9,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0,1,0,0,1,0,15,Readmission
1,500364,82442376,1,1,7,2,44,1,16,0,0,0,8,250.43,403,7,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0,1,0,0,0,1,35,No_readmission
2,16680,42519267,1,1,7,1,51,0,8,0,0,0,197,157,250,5,1.0,1.0,1.0,1.0,1.0,0.0,2.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0,1,0,0,0,1,45,No_readmission
3,35754,82637451,2,1,2,3,31,6,16,0,0,0,414,411,250,9,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0,0,1,0,0,0,1,55,Readmission
4,63768,114882984,1,1,7,5,73,0,12,0,0,0,428,492,250,8,1.0,1.0,1.0,1.0,1.0,0.0,1.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0,0,1,0,0,0,1,75,Readmission

In [41]:
# # create mapping dictionary for ordinal Encoding
# metformin_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# repaglinide_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# nateglinide_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# chlorpropamide_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up'
# }
# glimepiride_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# acetohexamide_map = {
#     'No': 0,
#     'Steady': 1
# }
# glipizide_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# glyburide_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# tolbutamide_map = {
#     'No': 0,
#     'Steady': 1
# }
# pioglitazone_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# rosiglitazone_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# acarbose_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# miglitol_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# troglitazone_map = {
#     'No': 0,
#     'Steady': 1
# }
# tolazamide_map = {
#     'No': 0,
#     'Steady': 1,
#     'Up': 2
# }
# examide_map = {
#     'No': 0
# }
# citoglipton_map = {
#     'No': 0
# }
# insulin_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# glyburide-metformin_map = {
#     'No': 0,
#     'Down': 1,
#     'Steady': 2,
#     'Up': 3
# }
# glipizide-metformin_map = {
#     'No': 0,
#     'Steady': 1
# }
# glimepiride-pioglitazone_map = {
#     'No': 0,
#     'Steady': 1
# }
# metformin-rosiglitazone_map = {
#     'No': 0
# }
# metformin-pioglitazone_map = {
#     'No': 0,
#     'Steady': 1
# }
# change_map = {
#     'No': 0,
#     'Ch': 1
# }
# diabetesMed_map = {
#     'No': 0,
#     'Yes': 1
# }

# # use mapping to do finish ordinal encoding
# clean_df.metformin = clean_df.metformin.map(metformin_map)
# clean_df.repaglinide = clean_df.repaglinide.map(repaglinide_map)
# clean_df.nateglinide = clean_df.nateglinide.map(nateglinide_map)
# clean_df.chlorpropamide = clean_df.chlorpropamide.map(chlorpropamide_map)
# clean_df.glimepiride = clean_df.glimepiride.map(glimepiride_map)
# clean_df.acetohexamide = clean_df.acetohexamide.map(acetohexamide_map)
# clean_df.glipizide = clean_df.glipizide.map(glipizide_map)
# clean_df.glyburide = clean_df.glyburide.map(glyburide_map)
# clean_df.tolbutamide = clean_df.tolbutamide.map(tolbutamide_map)
# clean_df.pioglitazone = clean_df.pioglitazone.map(pioglitazone_map)
# clean_df.rosiglitazone = clean_df.rosiglitazone.map(rosiglitazone_map)
# clean_df.acarbose = clean_df.acarbose.map(acarbose_map)
# clean_df.miglitol = clean_df.miglitol.map(miglitol_map)
# clean_df.troglitazone = clean_df.troglitazone.map(troglitazone_map)
# clean_df.tolazamide = clean_df.tolazamide.map(tolazamide_map)
# clean_df.examide = clean_df.examide.map(examide_map)
# clean_df.citoglipton = clean_df.citoglipton.map(citoglipton_map)
# clean_df.insulin = clean_df.insulin.map(insulin_map)
# clean_df.glyburide-metformin = clean_df.glyburide-metformin.map(glyburide-metformin_map)
# clean_df.glipizide-metformin = clean_df.glipizide-metformin.map(glipizide-metformin_map)
# clean_df.glimepiride-pioglitazone = clean_df.glimepiride-pioglitazone.map(glimepiride-pioglitazone_map)
# clean_df.metformin-rosiglitazone = clean_df.metformin-rosiglitazone.map(metformin-rosiglitazone_map)
# clean_df.metformin-pioglitazone = clean_df.metformin-pioglitazone.map(metformin-pioglitazone_map)
# clean_df.change = clean_df.change.map(change_map)
# clean_df.diabetesMed = clean_df.diabetesMed.map(diabetesMed_map)

In [42]:
#define dataset
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
#Get the array of the independent variables and target
X = df_new.iloc[:, :-1].values
y = df_new.iloc[:, -1].values

# print(X[:5, :5])
print(y[0:5])
# #get object of label encoder
# le = LabelEncoder()
# y = le.fit_transform(y)

# print(y[0:5])

['Readmission' 'No_readmission' 'No_readmission' 'Readmission'
 'Readmission']

In [43]:

#update X to scaled value
X = df_new.iloc[:, :-1].values

# print(X[0:5, 0:5])

# Normalization with MinMAxScaler

# build the scaler model
scaler = MinMaxScaler()

#fit using the train set
# scaler.fit(X)
scaler.fit(X)

#transform the test data
X_scaled = scaler.transform(X)

# verify minimum value of all features
# X_scaled.min(axis=0)

# X_scaled

In [44]:
#split the dataset
X = X_scaled
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, stratify=y)

Logistic Regression

In [45]:
#Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\ccuk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=0)

In [46]:
#Predicting the Test set results
y_pred = classifier.predict(X_test)

In [47]:
#Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[9211 2765]
 [5608 4862]]

0.6269713980219193

In [48]:
#Computing the accuracy with k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

C:\Users\ccuk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ccuk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ccuk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ccuk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ccuk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ccuk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ccuk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ccuk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ccuk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Accuracy: 62.56 %
Standard Deviation: 0.30 %

C:\Users\ccuk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Support Vector Model

In [49]:
# import numpy as np
# class SVM:
#     def _init_(self, learning_rate=0.001, lamba_param=0.01, n_iters=1000):
#         self.lr = learning_rate
#         self.lambda_param = lambda_param
#         self.n_iters = n_iters
#         self.w = None
#         self.b = None
        
#     def fit(self, X, y):
#         n_samples, n_features = X.shape
        
#         y_ = np.where(y <= 0, -1, 1)
        
#         # init the weight
#         self.w = np.zeros(n_features)
#         self.b = 0
        
#         for _ in range(self.n_iters):
#             for idx, x_i in enumerate(X):
#                 condition = y_[idx] * (np.dot(x_i, self.w) - self.b) >= 1
#                 if contion:
#                     self.w -= self.lr * (2 * self.lambda_param * self.w)
#                 else:
#                     self.w -= self.lr * (2 * self.lambda_param * self.w - np.dot(x_i, y_[idx]))
#                     self.b -= self.lr * y_[idx]
                
    
#     def predict(self, X):
#         approx = np.dot(X, self.w) - self.b
#         return np.sign(approx)
    
    
# #testing 
# if _name_ == "_main_":
#     #imports
#     from sklearn.model_selection import train_test_split
#     from sklearn import datasets
#     import matplotlib.pyplot as ply
    
#     X, y = datasets.make_blobs(
#         n_samples=50, n_features=2, centers=2, cluster_std=1.05, random_state=40
#     )
#     y = np.where(y == 0, -1, 1)
    
#     X_train, X_test, y_train, y_test = train_test_split(
#         X, y, test_size=0.2, random_stage=123
#     )
    
#     clf = SVM()
#     clf.fit(X_train, y_train)
#     predictions = clf.predict(X_test)
    
#     def accuracy(y_true, y_pred):
#         accuracy = np.sum(y_true == y_pred) / len(y_true)
#         return accuracy
    
#     print("SVM classification accuracy", accuracy(y_test, predictions))
    
#     def visualize_SVM():
#         def get_hyperplane_value(x, w, b, offset):
#             return(-w[0] * x + b + offset) / w[1]
        
#         fig = plt.figure()
#         ax = fig.add_subplot(1, 1, 1)
#         plt.scatter(X[:, 0], X[:, 1], marker="o", c=y)
        
#         x0_1 = np.amin(X[:, 0])
#         x1_1 = np.amax(X[:, 0])
        
#         x1_1 = get_hyperplane_value(x0_1, clf.w, clf.b, 0)
#         x1_2 = get_hyperplane_value(x0_2, clf.w, clf.b, 0)
        
#         x1_1 = get_hyperplane_value(x0_1, clf.w, clf.b, -1)
#         x1_2 = get_hyperplane_value(x0_2, clf.w, clf.b, -1)
        
#         x1_1_p = get_hyperplane_value(x0_1, clf.w, clf.b, 1)
#         x1_2_p = get_hyperplane_value(x0_2, clf.w, clf.b, 1)

In [50]:
# Import the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [51]:
# Split Dataset into X and Y
X = df_new.iloc[:, [2, 3]].values
y = df_new.iloc[:, 4].values

# print(X[0:5, 0:5])
# print(y[0:5])

#Split the X and Y Dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

#Perform Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


#Fit SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)


#Predict the Test Set Results
y_pred = classifier.predict(X_test)

# Make the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 5449     0     0     0     0     0   440     0     0     0   475     0]
 [  160     0     0     0     0     0    52     0     0     0     5     0]
 [   25     0     0     0     0     0    23     0     0     0     1     0]
 [  481     0     0     0     0     0    56     0     0     0     7     0]
 [   54     0     0     0     0     0   136     0     0     0     2     0]
 [   38     0     0     0     0     0   380     0     0     0     2     0]
 [ 1605     0     0     0     0     0 11101     0     0     0   397     0]
 [    1     0     0     0     0     0     2     0     0     0     1     0]
 [   13     0     0     0     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     1     0     0     0     0     0]
 [   51     0     0     0     0     0   145     0     0     0  1308     0]
 [   31     0     0     0     0     0     3     0     0     0     0     0]]

0.7955983248685735

In [ ]:
# df_new.apply(LabelEncoder().fit_transform)
# # df_new.head()

In [ ]:
# df_new.columns

In [ ]:
# X_data = df_new[['admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
#        'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
#        'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
#        'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
#        'tolazamide', 'examide', 'citoglipton', 'insulin',
#        'glyburide-metformin', 'glipizide-metformin',
#        'glimepiride-pioglitazone', 'metformin-rosiglitazone',
#        'metformin-pioglitazone', 'change', 'diabetesMed',
#        'race_AfricanAmerican', 'race_Asian', 'race_Caucasian', 'race_Hispanic',
#        'race_Other', 'gender_Female', 'gender_Male', 'avg_age']]

# Y_data = df_new['class']

In [ ]:
# X_Data = X_Data.apply(lambda x: (x - x.min(axis=0) ) / (x.max(axis=0) - x.min(axis=0)))

In [ ]:
# # x_Data

# from sklearn.preprocessing import MinMaxScaler

In [ ]:
# X_data.head(2)

In [ ]:
# scalar = MinMaxScaler()
# scalar.fit(X_data)
# X_data_new = scalar.transform(X_data)

In [ ]:
# #create data to scale: remove class columns 
# dfs = df_new.drop(['class'], axis = 1)

# dfs.head()

In [ ]:
#     from sklearn.preprocessing import MinMaxScaler
#     scaler = MinMaxScaler()
#     print(scaler.fit(dfs))
# MinMaxScaler()
#     print(scaler.dfs_max_)